# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='\u041c\u0430\u0440\u043a\u0430')),
                ('model', models.CharField(max_length=50, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c')),
                ('year', models.DateField(verbose_name='\u0413\u043e\u0434 \u0432\u044b\u043f\u0443\u0441\u043a\u0430')),
                ('characteristic', models.TextField(verbose_name='\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430')),
            ],
        ),
    ]
